/**
 * Created by jurgita on 2022-12-20.
 */

public with sharing class TH_CurseWordCheck {
    List<Case> CasesToCheck = new List<Case>();

    public void addCases(List<Case> CasesToAdd)
    {
        for (case aCase : casesToAdd)
        {
            if (String.isNotBlank(aCase.Description)
            {
                CasesToCheck.add(Case);
            }
        }

    }
public void updatecases()
{
    for (Case aCase : CasesToCheck)
}
}